package caiiiycuk.github.com

import caiiiycuk.github.com.api.Pull
import caiiiycuk.github.com.api.Status
import caiiiycuk.github.com.api.Statuses
import caiiiycuk.github.com.controller.UnlintHook
import caiiiycuk.github.com.engine.AdviceChecks

object Boot {

  val payload =
    """
{ "action" : "opened",
  "number" : 186,
  "pull_request" : { "_links" : { "comments" : { "href" : "https://api.github.com/repos/4geo/web-dev/issues/186/comments" },
          "html" : { "href" : "https://github.com/4geo/web-dev/pull/186" },
          "issue" : { "href" : "https://api.github.com/repos/4geo/web-dev/issues/186" },
          "review_comments" : { "href" : "https://api.github.com/repos/4geo/web-dev/pulls/186/comments" },
          "self" : { "href" : "https://api.github.com/repos/4geo/web-dev/pulls/186" }
        },
      "additions" : 3,
      "assignee" : null,
      "base" : { "label" : "4geo:release",
          "ref" : "release",
          "repo" : { "archive_url" : "https://api.github.com/repos/4geo/web-dev/{archive_format}{/ref}",
              "assignees_url" : "https://api.github.com/repos/4geo/web-dev/assignees{/user}",
              "blobs_url" : "https://api.github.com/repos/4geo/web-dev/git/blobs{/sha}",
              "branches_url" : "https://api.github.com/repos/4geo/web-dev/branches{/branch}",
              "clone_url" : "https://github.com/4geo/web-dev.git",
              "collaborators_url" : "https://api.github.com/repos/4geo/web-dev/collaborators{/collaborator}",
              "comments_url" : "https://api.github.com/repos/4geo/web-dev/comments{/number}",
              "commits_url" : "https://api.github.com/repos/4geo/web-dev/commits{/sha}",
              "compare_url" : "https://api.github.com/repos/4geo/web-dev/compare/{base}...{head}",
              "contents_url" : "https://api.github.com/repos/4geo/web-dev/contents/{+path}",
              "contributors_url" : "https://api.github.com/repos/4geo/web-dev/contributors",
              "created_at" : "2012-08-30T04:07:59Z",
              "default_branch" : "release",
              "description" : "web-dev",
              "downloads_url" : "https://api.github.com/repos/4geo/web-dev/downloads",
              "events_url" : "https://api.github.com/repos/4geo/web-dev/events",
              "fork" : false,
              "forks" : 5,
              "forks_count" : 5,
              "forks_url" : "https://api.github.com/repos/4geo/web-dev/forks",
              "full_name" : "4geo/web-dev",
              "git_commits_url" : "https://api.github.com/repos/4geo/web-dev/git/commits{/sha}",
              "git_refs_url" : "https://api.github.com/repos/4geo/web-dev/git/refs{/sha}",
              "git_tags_url" : "https://api.github.com/repos/4geo/web-dev/git/tags{/sha}",
              "git_url" : "git://github.com/4geo/web-dev.git",
              "has_downloads" : true,
              "has_issues" : false,
              "has_wiki" : false,
              "homepage" : null,
              "hooks_url" : "https://api.github.com/repos/4geo/web-dev/hooks",
              "html_url" : "https://github.com/4geo/web-dev",
              "id" : 5610301,
              "issue_comment_url" : "https://api.github.com/repos/4geo/web-dev/issues/comments/{number}",
              "issue_events_url" : "https://api.github.com/repos/4geo/web-dev/issues/events{/number}",
              "issues_url" : "https://api.github.com/repos/4geo/web-dev/issues{/number}",
              "keys_url" : "https://api.github.com/repos/4geo/web-dev/keys{/key_id}",
              "labels_url" : "https://api.github.com/repos/4geo/web-dev/labels{/name}",
              "language" : "JavaScript",
              "languages_url" : "https://api.github.com/repos/4geo/web-dev/languages",
              "master_branch" : "release",
              "merges_url" : "https://api.github.com/repos/4geo/web-dev/merges",
              "milestones_url" : "https://api.github.com/repos/4geo/web-dev/milestones{/number}",
              "mirror_url" : null,
              "name" : "web-dev",
              "notifications_url" : "https://api.github.com/repos/4geo/web-dev/notifications{?since,all,participating}",
              "open_issues" : 4,
              "open_issues_count" : 4,
              "owner" : { "avatar_url" : "https://secure.gravatar.com/avatar/d41d8cd98f00b204e9800998ecf8427e?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-org-420.png",
                  "events_url" : "https://api.github.com/users/4geo/events{/privacy}",
                  "followers_url" : "https://api.github.com/users/4geo/followers",
                  "following_url" : "https://api.github.com/users/4geo/following",
                  "gists_url" : "https://api.github.com/users/4geo/gists{/gist_id}",
                  "gravatar_id" : "d41d8cd98f00b204e9800998ecf8427e",
                  "html_url" : "https://github.com/4geo",
                  "id" : 2161276,
                  "login" : "4geo",
                  "organizations_url" : "https://api.github.com/users/4geo/orgs",
                  "received_events_url" : "https://api.github.com/users/4geo/received_events",
                  "repos_url" : "https://api.github.com/users/4geo/repos",
                  "starred_url" : "https://api.github.com/users/4geo/starred{/owner}{/repo}",
                  "subscriptions_url" : "https://api.github.com/users/4geo/subscriptions",
                  "type" : "Organization",
                  "url" : "https://api.github.com/users/4geo"
                },
              "private" : true,
              "pulls_url" : "https://api.github.com/repos/4geo/web-dev/pulls{/number}",
              "pushed_at" : "2013-02-22T06:50:05Z",
              "size" : 660,
              "ssh_url" : "git@github.com:4geo/web-dev.git",
              "stargazers_url" : "https://api.github.com/repos/4geo/web-dev/stargazers",
              "statuses_url" : "https://api.github.com/repos/4geo/web-dev/statuses/{sha}",
              "subscribers_url" : "https://api.github.com/repos/4geo/web-dev/subscribers",
              "subscription_url" : "https://api.github.com/repos/4geo/web-dev/subscription",
              "svn_url" : "https://github.com/4geo/web-dev",
              "tags_url" : "https://api.github.com/repos/4geo/web-dev/tags{/tag}",
              "teams_url" : "https://api.github.com/repos/4geo/web-dev/teams",
              "trees_url" : "https://api.github.com/repos/4geo/web-dev/git/trees{/sha}",
              "updated_at" : "2013-02-22T06:50:06Z",
              "url" : "https://api.github.com/repos/4geo/web-dev",
              "watchers" : 0,
              "watchers_count" : 0
            },
          "sha" : "f9e390dd24b606f46f749791f5d03b58e5dddfc7",
          "user" : { "avatar_url" : "https://secure.gravatar.com/avatar/d41d8cd98f00b204e9800998ecf8427e?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-org-420.png",
              "events_url" : "https://api.github.com/users/4geo/events{/privacy}",
              "followers_url" : "https://api.github.com/users/4geo/followers",
              "following_url" : "https://api.github.com/users/4geo/following",
              "gists_url" : "https://api.github.com/users/4geo/gists{/gist_id}",
              "gravatar_id" : "d41d8cd98f00b204e9800998ecf8427e",
              "html_url" : "https://github.com/4geo",
              "id" : 2161276,
              "login" : "4geo",
              "organizations_url" : "https://api.github.com/users/4geo/orgs",
              "received_events_url" : "https://api.github.com/users/4geo/received_events",
              "repos_url" : "https://api.github.com/users/4geo/repos",
              "starred_url" : "https://api.github.com/users/4geo/starred{/owner}{/repo}",
              "subscriptions_url" : "https://api.github.com/users/4geo/subscriptions",
              "type" : "Organization",
              "url" : "https://api.github.com/users/4geo"
            }
        },
      "body" : "",
      "changed_files" : 1,
      "closed_at" : null,
      "comments" : 0,
      "comments_url" : "https://api.github.com/repos/4geo/web-dev/issues/186/comments",
      "commits" : 3,
      "commits_url" : "https://github.com/4geo/web-dev/pull/186/commits",
      "created_at" : "2013-02-24T13:43:14Z",
      "deletions" : 1,
      "diff_url" : "https://github.com/4geo/web-dev/pull/186.diff",
      "head" : { "label" : "litehause:release",
          "ref" : "release",
          "repo" : { "archive_url" : "https://api.github.com/repos/litehause/web-dev/{archive_format}{/ref}",
              "assignees_url" : "https://api.github.com/repos/litehause/web-dev/assignees{/user}",
              "blobs_url" : "https://api.github.com/repos/litehause/web-dev/git/blobs{/sha}",
              "branches_url" : "https://api.github.com/repos/litehause/web-dev/branches{/branch}",
              "clone_url" : "https://github.com/litehause/web-dev.git",
              "collaborators_url" : "https://api.github.com/repos/litehause/web-dev/collaborators{/collaborator}",
              "comments_url" : "https://api.github.com/repos/litehause/web-dev/comments{/number}",
              "commits_url" : "https://api.github.com/repos/litehause/web-dev/commits{/sha}",
              "compare_url" : "https://api.github.com/repos/litehause/web-dev/compare/{base}...{head}",
              "contents_url" : "https://api.github.com/repos/litehause/web-dev/contents/{+path}",
              "contributors_url" : "https://api.github.com/repos/litehause/web-dev/contributors",
              "created_at" : "2012-09-03T03:37:43Z",
              "default_branch" : "release",
              "description" : "web-dev",
              "downloads_url" : "https://api.github.com/repos/litehause/web-dev/downloads",
              "events_url" : "https://api.github.com/repos/litehause/web-dev/events",
              "fork" : true,
              "forks" : 0,
              "forks_count" : 0,
              "forks_url" : "https://api.github.com/repos/litehause/web-dev/forks",
              "full_name" : "litehause/web-dev",
              "git_commits_url" : "https://api.github.com/repos/litehause/web-dev/git/commits{/sha}",
              "git_refs_url" : "https://api.github.com/repos/litehause/web-dev/git/refs{/sha}",
              "git_tags_url" : "https://api.github.com/repos/litehause/web-dev/git/tags{/sha}",
              "git_url" : "git://github.com/litehause/web-dev.git",
              "has_downloads" : true,
              "has_issues" : false,
              "has_wiki" : false,
              "homepage" : null,
              "hooks_url" : "https://api.github.com/repos/litehause/web-dev/hooks",
              "html_url" : "https://github.com/litehause/web-dev",
              "id" : 5654242,
              "issue_comment_url" : "https://api.github.com/repos/litehause/web-dev/issues/comments/{number}",
              "issue_events_url" : "https://api.github.com/repos/litehause/web-dev/issues/events{/number}",
              "issues_url" : "https://api.github.com/repos/litehause/web-dev/issues{/number}",
              "keys_url" : "https://api.github.com/repos/litehause/web-dev/keys{/key_id}",
              "labels_url" : "https://api.github.com/repos/litehause/web-dev/labels{/name}",
              "language" : "JavaScript",
              "languages_url" : "https://api.github.com/repos/litehause/web-dev/languages",
              "master_branch" : "release",
              "merges_url" : "https://api.github.com/repos/litehause/web-dev/merges",
              "milestones_url" : "https://api.github.com/repos/litehause/web-dev/milestones{/number}",
              "mirror_url" : null,
              "name" : "web-dev",
              "notifications_url" : "https://api.github.com/repos/litehause/web-dev/notifications{?since,all,participating}",
              "open_issues" : 0,
              "open_issues_count" : 0,
              "owner" : { "avatar_url" : "https://secure.gravatar.com/avatar/a7e9ec4ac815d0abdb400010c3faaaf5?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png",
                  "events_url" : "https://api.github.com/users/litehause/events{/privacy}",
                  "followers_url" : "https://api.github.com/users/litehause/followers",
                  "following_url" : "https://api.github.com/users/litehause/following",
                  "gists_url" : "https://api.github.com/users/litehause/gists{/gist_id}",
                  "gravatar_id" : "a7e9ec4ac815d0abdb400010c3faaaf5",
                  "html_url" : "https://github.com/litehause",
                  "id" : 2267638,
                  "login" : "litehause",
                  "organizations_url" : "https://api.github.com/users/litehause/orgs",
                  "received_events_url" : "https://api.github.com/users/litehause/received_events",
                  "repos_url" : "https://api.github.com/users/litehause/repos",
                  "starred_url" : "https://api.github.com/users/litehause/starred{/owner}{/repo}",
                  "subscriptions_url" : "https://api.github.com/users/litehause/subscriptions",
                  "type" : "User",
                  "url" : "https://api.github.com/users/litehause"
                },
              "private" : true,
              "pulls_url" : "https://api.github.com/repos/litehause/web-dev/pulls{/number}",
              "pushed_at" : "2013-02-22T05:39:29Z",
              "size" : 544,
              "ssh_url" : "git@github.com:litehause/web-dev.git",
              "stargazers_url" : "https://api.github.com/repos/litehause/web-dev/stargazers",
              "statuses_url" : "https://api.github.com/repos/litehause/web-dev/statuses/{sha}",
              "subscribers_url" : "https://api.github.com/repos/litehause/web-dev/subscribers",
              "subscription_url" : "https://api.github.com/repos/litehause/web-dev/subscription",
              "svn_url" : "https://github.com/litehause/web-dev",
              "tags_url" : "https://api.github.com/repos/litehause/web-dev/tags{/tag}",
              "teams_url" : "https://api.github.com/repos/litehause/web-dev/teams",
              "trees_url" : "https://api.github.com/repos/litehause/web-dev/git/trees{/sha}",
              "updated_at" : "2013-02-24T13:43:14Z",
              "url" : "https://api.github.com/repos/litehause/web-dev",
              "watchers" : 0,
              "watchers_count" : 0
            },
          "sha" : "06dabeb4967ce47c6e63f7d7e5b56ee2f10a97e5",
          "user" : { "avatar_url" : "https://secure.gravatar.com/avatar/a7e9ec4ac815d0abdb400010c3faaaf5?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png",
              "events_url" : "https://api.github.com/users/litehause/events{/privacy}",
              "followers_url" : "https://api.github.com/users/litehause/followers",
              "following_url" : "https://api.github.com/users/litehause/following",
              "gists_url" : "https://api.github.com/users/litehause/gists{/gist_id}",
              "gravatar_id" : "a7e9ec4ac815d0abdb400010c3faaaf5",
              "html_url" : "https://github.com/litehause",
              "id" : 2267638,
              "login" : "litehause",
              "organizations_url" : "https://api.github.com/users/litehause/orgs",
              "received_events_url" : "https://api.github.com/users/litehause/received_events",
              "repos_url" : "https://api.github.com/users/litehause/repos",
              "starred_url" : "https://api.github.com/users/litehause/starred{/owner}{/repo}",
              "subscriptions_url" : "https://api.github.com/users/litehause/subscriptions",
              "type" : "User",
              "url" : "https://api.github.com/users/litehause"
            }
        },
      "html_url" : "https://github.com/4geo/web-dev/pull/186",
      "id" : 4293526,
      "issue_url" : "https://github.com/4geo/web-dev/issues/186",
      "merge_commit_sha" : null,
      "mergeable" : null,
      "mergeable_state" : "unknown",
      "merged" : false,
      "merged_at" : null,
      "merged_by" : null,
      "milestone" : null,
      "number" : 186,
      "patch_url" : "https://github.com/4geo/web-dev/pull/186.patch",
      "review_comment_url" : "/repos/4geo/web-dev/pulls/comments/{number}",
      "review_comments" : 0,
      "review_comments_url" : "https://github.com/4geo/web-dev/pull/186/comments",
      "state" : "open",
      "title" : "Release",
      "updated_at" : "2013-02-24T13:43:14Z",
      "url" : "https://api.github.com/repos/4geo/web-dev/pulls/186",
      "user" : { "avatar_url" : "https://secure.gravatar.com/avatar/c3e2bd444cac0a23aa591921b4d1a8f1?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png",
          "events_url" : "https://api.github.com/users/caiiiycuk/events{/privacy}",
          "followers_url" : "https://api.github.com/users/caiiiycuk/followers",
          "following_url" : "https://api.github.com/users/caiiiycuk/following",
          "gists_url" : "https://api.github.com/users/caiiiycuk/gists{/gist_id}",
          "gravatar_id" : "c3e2bd444cac0a23aa591921b4d1a8f1",
          "html_url" : "https://github.com/caiiiycuk",
          "id" : 1727152,
          "login" : "caiiiycuk",
          "organizations_url" : "https://api.github.com/users/caiiiycuk/orgs",
          "received_events_url" : "https://api.github.com/users/caiiiycuk/received_events",
          "repos_url" : "https://api.github.com/users/caiiiycuk/repos",
          "starred_url" : "https://api.github.com/users/caiiiycuk/starred{/owner}{/repo}",
          "subscriptions_url" : "https://api.github.com/users/caiiiycuk/subscriptions",
          "type" : "User",
          "url" : "https://api.github.com/users/caiiiycuk"
        }
    },
  "repository" : { "archive_url" : "https://api.github.com/repos/4geo/web-dev/{archive_format}{/ref}",
      "assignees_url" : "https://api.github.com/repos/4geo/web-dev/assignees{/user}",
      "blobs_url" : "https://api.github.com/repos/4geo/web-dev/git/blobs{/sha}",
      "branches_url" : "https://api.github.com/repos/4geo/web-dev/branches{/branch}",
      "clone_url" : "https://github.com/4geo/web-dev.git",
      "collaborators_url" : "https://api.github.com/repos/4geo/web-dev/collaborators{/collaborator}",
      "comments_url" : "https://api.github.com/repos/4geo/web-dev/comments{/number}",
      "commits_url" : "https://api.github.com/repos/4geo/web-dev/commits{/sha}",
      "compare_url" : "https://api.github.com/repos/4geo/web-dev/compare/{base}...{head}",
      "contents_url" : "https://api.github.com/repos/4geo/web-dev/contents/{+path}",
      "contributors_url" : "https://api.github.com/repos/4geo/web-dev/contributors",
      "created_at" : "2012-08-30T04:07:59Z",
      "default_branch" : "release",
      "description" : "web-dev",
      "downloads_url" : "https://api.github.com/repos/4geo/web-dev/downloads",
      "events_url" : "https://api.github.com/repos/4geo/web-dev/events",
      "fork" : false,
      "forks" : 5,
      "forks_count" : 5,
      "forks_url" : "https://api.github.com/repos/4geo/web-dev/forks",
      "full_name" : "4geo/web-dev",
      "git_commits_url" : "https://api.github.com/repos/4geo/web-dev/git/commits{/sha}",
      "git_refs_url" : "https://api.github.com/repos/4geo/web-dev/git/refs{/sha}",
      "git_tags_url" : "https://api.github.com/repos/4geo/web-dev/git/tags{/sha}",
      "git_url" : "git://github.com/4geo/web-dev.git",
      "has_downloads" : true,
      "has_issues" : false,
      "has_wiki" : false,
      "homepage" : null,
      "hooks_url" : "https://api.github.com/repos/4geo/web-dev/hooks",
      "html_url" : "https://github.com/4geo/web-dev",
      "id" : 5610301,
      "issue_comment_url" : "https://api.github.com/repos/4geo/web-dev/issues/comments/{number}",
      "issue_events_url" : "https://api.github.com/repos/4geo/web-dev/issues/events{/number}",
      "issues_url" : "https://api.github.com/repos/4geo/web-dev/issues{/number}",
      "keys_url" : "https://api.github.com/repos/4geo/web-dev/keys{/key_id}",
      "labels_url" : "https://api.github.com/repos/4geo/web-dev/labels{/name}",
      "language" : "JavaScript",
      "languages_url" : "https://api.github.com/repos/4geo/web-dev/languages",
      "master_branch" : "release",
      "merges_url" : "https://api.github.com/repos/4geo/web-dev/merges",
      "milestones_url" : "https://api.github.com/repos/4geo/web-dev/milestones{/number}",
      "mirror_url" : null,
      "name" : "web-dev",
      "notifications_url" : "https://api.github.com/repos/4geo/web-dev/notifications{?since,all,participating}",
      "open_issues" : 4,
      "open_issues_count" : 4,
      "owner" : { "avatar_url" : "https://secure.gravatar.com/avatar/d41d8cd98f00b204e9800998ecf8427e?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-org-420.png",
          "events_url" : "https://api.github.com/users/4geo/events{/privacy}",
          "followers_url" : "https://api.github.com/users/4geo/followers",
          "following_url" : "https://api.github.com/users/4geo/following",
          "gists_url" : "https://api.github.com/users/4geo/gists{/gist_id}",
          "gravatar_id" : "d41d8cd98f00b204e9800998ecf8427e",
          "html_url" : "https://github.com/4geo",
          "id" : 2161276,
          "login" : "4geo",
          "organizations_url" : "https://api.github.com/users/4geo/orgs",
          "received_events_url" : "https://api.github.com/users/4geo/received_events",
          "repos_url" : "https://api.github.com/users/4geo/repos",
          "starred_url" : "https://api.github.com/users/4geo/starred{/owner}{/repo}",
          "subscriptions_url" : "https://api.github.com/users/4geo/subscriptions",
          "type" : "Organization",
          "url" : "https://api.github.com/users/4geo"
        },
      "private" : true,
      "pulls_url" : "https://api.github.com/repos/4geo/web-dev/pulls{/number}",
      "pushed_at" : "2013-02-22T06:50:05Z",
      "size" : 660,
      "ssh_url" : "git@github.com:4geo/web-dev.git",
      "stargazers_url" : "https://api.github.com/repos/4geo/web-dev/stargazers",
      "statuses_url" : "https://api.github.com/repos/4geo/web-dev/statuses/{sha}",
      "subscribers_url" : "https://api.github.com/repos/4geo/web-dev/subscribers",
      "subscription_url" : "https://api.github.com/repos/4geo/web-dev/subscription",
      "svn_url" : "https://github.com/4geo/web-dev",
      "tags_url" : "https://api.github.com/repos/4geo/web-dev/tags{/tag}",
      "teams_url" : "https://api.github.com/repos/4geo/web-dev/teams",
      "trees_url" : "https://api.github.com/repos/4geo/web-dev/git/trees{/sha}",
      "updated_at" : "2013-02-22T06:50:06Z",
      "url" : "https://api.github.com/repos/4geo/web-dev",
      "watchers" : 0,
      "watchers_count" : 0
    },
  "sender" : { "avatar_url" : "https://secure.gravatar.com/avatar/c3e2bd444cac0a23aa591921b4d1a8f1?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png",
      "events_url" : "https://api.github.com/users/caiiiycuk/events{/privacy}",
      "followers_url" : "https://api.github.com/users/caiiiycuk/followers",
      "following_url" : "https://api.github.com/users/caiiiycuk/following",
      "gists_url" : "https://api.github.com/users/caiiiycuk/gists{/gist_id}",
      "gravatar_id" : "c3e2bd444cac0a23aa591921b4d1a8f1",
      "html_url" : "https://github.com/caiiiycuk",
      "id" : 1727152,
      "login" : "caiiiycuk",
      "organizations_url" : "https://api.github.com/users/caiiiycuk/orgs",
      "received_events_url" : "https://api.github.com/users/caiiiycuk/received_events",
      "repos_url" : "https://api.github.com/users/caiiiycuk/repos",
      "starred_url" : "https://api.github.com/users/caiiiycuk/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/caiiiycuk/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/caiiiycuk"
    }
}
"""

  val payload2 =
    """
{ "action": "opened", "number": 187, "pull_request": { "_links": { "comments": { "href": "https://api.github.com/repos/4geo/web-dev/issues/187/comments" }, "html": { "href": "https://github.com/4geo/web-dev/pull/187" }, "issue": { "href": "https://api.github.com/repos/4geo/web-dev/issues/187" }, "review_comments": { "href": "https://api.github.com/repos/4geo/web-dev/pulls/187/comments" }, "self": { "href": "https://api.github.com/repos/4geo/web-dev/pulls/187" } }, "additions": 0, "assignee": null, "base": { "label": "4geo:release", "ref": "release", "repo": { "archive_url": "https://api.github.com/repos/4geo/web-dev/{archive_format}{/ref}", "assignees_url": "https://api.github.com/repos/4geo/web-dev/assignees{/user}", "blobs_url": "https://api.github.com/repos/4geo/web-dev/git/blobs{/sha}", "branches_url": "https://api.github.com/repos/4geo/web-dev/branches{/branch}", "clone_url": "https://github.com/4geo/web-dev.git", "collaborators_url": "https://api.github.com/repos/4geo/web-dev/collaborators{/collaborator}", "comments_url": "https://api.github.com/repos/4geo/web-dev/comments{/number}", "commits_url": "https://api.github.com/repos/4geo/web-dev/commits{/sha}", "compare_url": "https://api.github.com/repos/4geo/web-dev/compare/{base}...{head}", "contents_url": "https://api.github.com/repos/4geo/web-dev/contents/{+path}", "contributors_url": "https://api.github.com/repos/4geo/web-dev/contributors", "created_at": "2012-08-30T04:07:59Z", "default_branch": "release", "description": "web-dev", "downloads_url": "https://api.github.com/repos/4geo/web-dev/downloads", "events_url": "https://api.github.com/repos/4geo/web-dev/events", "fork": false, "forks": 5, "forks_count": 5, "forks_url": "https://api.github.com/repos/4geo/web-dev/forks", "full_name": "4geo/web-dev", "git_commits_url": "https://api.github.com/repos/4geo/web-dev/git/commits{/sha}", "git_refs_url": "https://api.github.com/repos/4geo/web-dev/git/refs{/sha}", "git_tags_url": "https://api.github.com/repos/4geo/web-dev/git/tags{/sha}", "git_url": "git://github.com/4geo/web-dev.git", "has_downloads": true, "has_issues": false, "has_wiki": false, "homepage": null, "hooks_url": "https://api.github.com/repos/4geo/web-dev/hooks", "html_url": "https://github.com/4geo/web-dev", "id": 5610301, "issue_comment_url": "https://api.github.com/repos/4geo/web-dev/issues/comments/{number}", "issue_events_url": "https://api.github.com/repos/4geo/web-dev/issues/events{/number}", "issues_url": "https://api.github.com/repos/4geo/web-dev/issues{/number}", "keys_url": "https://api.github.com/repos/4geo/web-dev/keys{/key_id}", "labels_url": "https://api.github.com/repos/4geo/web-dev/labels{/name}", "language": "JavaScript", "languages_url": "https://api.github.com/repos/4geo/web-dev/languages", "master_branch": "release", "merges_url": "https://api.github.com/repos/4geo/web-dev/merges", "milestones_url": "https://api.github.com/repos/4geo/web-dev/milestones{/number}", "mirror_url": null, "name": "web-dev", "notifications_url": "https://api.github.com/repos/4geo/web-dev/notifications{?since,all,participating}", "open_issues": 4, "open_issues_count": 4, "owner": { "avatar_url": "https://secure.gravatar.com/avatar/d41d8cd98f00b204e9800998ecf8427e?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-org-420.png", "events_url": "https://api.github.com/users/4geo/events{/privacy}", "followers_url": "https://api.github.com/users/4geo/followers", "following_url": "https://api.github.com/users/4geo/following", "gists_url": "https://api.github.com/users/4geo/gists{/gist_id}", "gravatar_id": "d41d8cd98f00b204e9800998ecf8427e", "html_url": "https://github.com/4geo", "id": 2161276, "login": "4geo", "organizations_url": "https://api.github.com/users/4geo/orgs", "received_events_url": "https://api.github.com/users/4geo/received_events", "repos_url": "https://api.github.com/users/4geo/repos", "starred_url": "https://api.github.com/users/4geo/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/4geo/subscriptions", "type": "Organization", "url": "https://api.github.com/users/4geo" }, "private": true, "pulls_url": "https://api.github.com/repos/4geo/web-dev/pulls{/number}", "pushed_at": "2013-02-22T06:50:05Z", "size": 660, "ssh_url": "git@github.com:4geo/web-dev.git", "stargazers_url": "https://api.github.com/repos/4geo/web-dev/stargazers", "statuses_url": "https://api.github.com/repos/4geo/web-dev/statuses/{sha}", "subscribers_url": "https://api.github.com/repos/4geo/web-dev/subscribers", "subscription_url": "https://api.github.com/repos/4geo/web-dev/subscription", "svn_url": "https://github.com/4geo/web-dev", "tags_url": "https://api.github.com/repos/4geo/web-dev/tags{/tag}", "teams_url": "https://api.github.com/repos/4geo/web-dev/teams", "trees_url": "https://api.github.com/repos/4geo/web-dev/git/trees{/sha}", "updated_at": "2013-02-22T06:50:06Z", "url": "https://api.github.com/repos/4geo/web-dev", "watchers": 0, "watchers_count": 0 }, "sha": "f9e390dd24b606f46f749791f5d03b58e5dddfc7", "user": { "avatar_url": "https://secure.gravatar.com/avatar/d41d8cd98f00b204e9800998ecf8427e?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-org-420.png", "events_url": "https://api.github.com/users/4geo/events{/privacy}", "followers_url": "https://api.github.com/users/4geo/followers", "following_url": "https://api.github.com/users/4geo/following", "gists_url": "https://api.github.com/users/4geo/gists{/gist_id}", "gravatar_id": "d41d8cd98f00b204e9800998ecf8427e", "html_url": "https://github.com/4geo", "id": 2161276, "login": "4geo", "organizations_url": "https://api.github.com/users/4geo/orgs", "received_events_url": "https://api.github.com/users/4geo/received_events", "repos_url": "https://api.github.com/users/4geo/repos", "starred_url": "https://api.github.com/users/4geo/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/4geo/subscriptions", "type": "Organization", "url": "https://api.github.com/users/4geo" } }, "body": "", "changed_files": 2, "closed_at": null, "comments": 0, "comments_url": "https://api.github.com/repos/4geo/web-dev/issues/187/comments", "commits": 1, "commits_url": "https://github.com/4geo/web-dev/pull/187/commits", "created_at": "2013-02-25T01:54:30Z", "deletions": 142, "diff_url": "https://github.com/4geo/web-dev/pull/187.diff", "head": { "label": "caiiiycuk:events", "ref": "events", "repo": { "archive_url": "https://api.github.com/repos/caiiiycuk/web-dev/{archive_format}{/ref}", "assignees_url": "https://api.github.com/repos/caiiiycuk/web-dev/assignees{/user}", "blobs_url": "https://api.github.com/repos/caiiiycuk/web-dev/git/blobs{/sha}", "branches_url": "https://api.github.com/repos/caiiiycuk/web-dev/branches{/branch}", "clone_url": "https://github.com/caiiiycuk/web-dev.git", "collaborators_url": "https://api.github.com/repos/caiiiycuk/web-dev/collaborators{/collaborator}", "comments_url": "https://api.github.com/repos/caiiiycuk/web-dev/comments{/number}", "commits_url": "https://api.github.com/repos/caiiiycuk/web-dev/commits{/sha}", "compare_url": "https://api.github.com/repos/caiiiycuk/web-dev/compare/{base}...{head}", "contents_url": "https://api.github.com/repos/caiiiycuk/web-dev/contents/{+path}", "contributors_url": "https://api.github.com/repos/caiiiycuk/web-dev/contributors", "created_at": "2012-09-11T03:03:45Z", "default_branch": "release", "description": "web-dev", "downloads_url": "https://api.github.com/repos/caiiiycuk/web-dev/downloads", "events_url": "https://api.github.com/repos/caiiiycuk/web-dev/events", "fork": true, "forks": 0, "forks_count": 0, "forks_url": "https://api.github.com/repos/caiiiycuk/web-dev/forks", "full_name": "caiiiycuk/web-dev", "git_commits_url": "https://api.github.com/repos/caiiiycuk/web-dev/git/commits{/sha}", "git_refs_url": "https://api.github.com/repos/caiiiycuk/web-dev/git/refs{/sha}", "git_tags_url": "https://api.github.com/repos/caiiiycuk/web-dev/git/tags{/sha}", "git_url": "git://github.com/caiiiycuk/web-dev.git", "has_downloads": true, "has_issues": false, "has_wiki": false, "homepage": null, "hooks_url": "https://api.github.com/repos/caiiiycuk/web-dev/hooks", "html_url": "https://github.com/caiiiycuk/web-dev", "id": 5759212, "issue_comment_url": "https://api.github.com/repos/caiiiycuk/web-dev/issues/comments/{number}", "issue_events_url": "https://api.github.com/repos/caiiiycuk/web-dev/issues/events{/number}", "issues_url": "https://api.github.com/repos/caiiiycuk/web-dev/issues{/number}", "keys_url": "https://api.github.com/repos/caiiiycuk/web-dev/keys{/key_id}", "labels_url": "https://api.github.com/repos/caiiiycuk/web-dev/labels{/name}", "language": "JavaScript", "languages_url": "https://api.github.com/repos/caiiiycuk/web-dev/languages", "master_branch": "release", "merges_url": "https://api.github.com/repos/caiiiycuk/web-dev/merges", "milestones_url": "https://api.github.com/repos/caiiiycuk/web-dev/milestones{/number}", "mirror_url": null, "name": "web-dev", "notifications_url": "https://api.github.com/repos/caiiiycuk/web-dev/notifications{?since,all,participating}", "open_issues": 0, "open_issues_count": 0, "owner": { "avatar_url": "https://secure.gravatar.com/avatar/c3e2bd444cac0a23aa591921b4d1a8f1?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png", "events_url": "https://api.github.com/users/caiiiycuk/events{/privacy}", "followers_url": "https://api.github.com/users/caiiiycuk/followers", "following_url": "https://api.github.com/users/caiiiycuk/following", "gists_url": "https://api.github.com/users/caiiiycuk/gists{/gist_id}", "gravatar_id": "c3e2bd444cac0a23aa591921b4d1a8f1", "html_url": "https://github.com/caiiiycuk", "id": 1727152, "login": "caiiiycuk", "organizations_url": "https://api.github.com/users/caiiiycuk/orgs", "received_events_url": "https://api.github.com/users/caiiiycuk/received_events", "repos_url": "https://api.github.com/users/caiiiycuk/repos", "starred_url": "https://api.github.com/users/caiiiycuk/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/caiiiycuk/subscriptions", "type": "User", "url": "https://api.github.com/users/caiiiycuk" }, "private": true, "pulls_url": "https://api.github.com/repos/caiiiycuk/web-dev/pulls{/number}", "pushed_at": "2013-02-25T01:54:07Z", "size": 340, "ssh_url": "git@github.com:caiiiycuk/web-dev.git", "stargazers_url": "https://api.github.com/repos/caiiiycuk/web-dev/stargazers", "statuses_url": "https://api.github.com/repos/caiiiycuk/web-dev/statuses/{sha}", "subscribers_url": "https://api.github.com/repos/caiiiycuk/web-dev/subscribers", "subscription_url": "https://api.github.com/repos/caiiiycuk/web-dev/subscription", "svn_url": "https://github.com/caiiiycuk/web-dev", "tags_url": "https://api.github.com/repos/caiiiycuk/web-dev/tags{/tag}", "teams_url": "https://api.github.com/repos/caiiiycuk/web-dev/teams", "trees_url": "https://api.github.com/repos/caiiiycuk/web-dev/git/trees{/sha}", "updated_at": "2013-02-25T01:54:30Z", "url": "https://api.github.com/repos/caiiiycuk/web-dev", "watchers": 0, "watchers_count": 0 }, "sha": "b0a864050b83f3a9bdb1fdbf78e36d6510c08204", "user": { "avatar_url": "https://secure.gravatar.com/avatar/c3e2bd444cac0a23aa591921b4d1a8f1?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png", "events_url": "https://api.github.com/users/caiiiycuk/events{/privacy}", "followers_url": "https://api.github.com/users/caiiiycuk/followers", "following_url": "https://api.github.com/users/caiiiycuk/following", "gists_url": "https://api.github.com/users/caiiiycuk/gists{/gist_id}", "gravatar_id": "c3e2bd444cac0a23aa591921b4d1a8f1", "html_url": "https://github.com/caiiiycuk", "id": 1727152, "login": "caiiiycuk", "organizations_url": "https://api.github.com/users/caiiiycuk/orgs", "received_events_url": "https://api.github.com/users/caiiiycuk/received_events", "repos_url": "https://api.github.com/users/caiiiycuk/repos", "starred_url": "https://api.github.com/users/caiiiycuk/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/caiiiycuk/subscriptions", "type": "User", "url": "https://api.github.com/users/caiiiycuk" } }, "html_url": "https://github.com/4geo/web-dev/pull/187", "id": 4296543, "issue_url": "https://github.com/4geo/web-dev/issues/187", "merge_commit_sha": null, "mergeable": null, "mergeable_state": "unknown", "merged": false, "merged_at": null, "merged_by": null, "milestone": null, "number": 187, "patch_url": "https://github.com/4geo/web-dev/pull/187.patch", "review_comment_url": "/repos/4geo/web-dev/pulls/comments/{number}", "review_comments": 0, "review_comments_url": "https://github.com/4geo/web-dev/pull/187/comments", "state": "open", "title": "Test 1", "updated_at": "2013-02-25T01:54:30Z", "url": "https://api.github.com/repos/4geo/web-dev/pulls/187", "user": { "avatar_url": "https://secure.gravatar.com/avatar/c3e2bd444cac0a23aa591921b4d1a8f1?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png", "events_url": "https://api.github.com/users/caiiiycuk/events{/privacy}", "followers_url": "https://api.github.com/users/caiiiycuk/followers", "following_url": "https://api.github.com/users/caiiiycuk/following", "gists_url": "https://api.github.com/users/caiiiycuk/gists{/gist_id}", "gravatar_id": "c3e2bd444cac0a23aa591921b4d1a8f1", "html_url": "https://github.com/caiiiycuk", "id": 1727152, "login": "caiiiycuk", "organizations_url": "https://api.github.com/users/caiiiycuk/orgs", "received_events_url": "https://api.github.com/users/caiiiycuk/received_events", "repos_url": "https://api.github.com/users/caiiiycuk/repos", "starred_url": "https://api.github.com/users/caiiiycuk/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/caiiiycuk/subscriptions", "type": "User", "url": "https://api.github.com/users/caiiiycuk" } }, "repository": { "archive_url": "https://api.github.com/repos/4geo/web-dev/{archive_format}{/ref}", "assignees_url": "https://api.github.com/repos/4geo/web-dev/assignees{/user}", "blobs_url": "https://api.github.com/repos/4geo/web-dev/git/blobs{/sha}", "branches_url": "https://api.github.com/repos/4geo/web-dev/branches{/branch}", "clone_url": "https://github.com/4geo/web-dev.git", "collaborators_url": "https://api.github.com/repos/4geo/web-dev/collaborators{/collaborator}", "comments_url": "https://api.github.com/repos/4geo/web-dev/comments{/number}", "commits_url": "https://api.github.com/repos/4geo/web-dev/commits{/sha}", "compare_url": "https://api.github.com/repos/4geo/web-dev/compare/{base}...{head}", "contents_url": "https://api.github.com/repos/4geo/web-dev/contents/{+path}", "contributors_url": "https://api.github.com/repos/4geo/web-dev/contributors", "created_at": "2012-08-30T04:07:59Z", "default_branch": "release", "description": "web-dev", "downloads_url": "https://api.github.com/repos/4geo/web-dev/downloads", "events_url": "https://api.github.com/repos/4geo/web-dev/events", "fork": false, "forks": 5, "forks_count": 5, "forks_url": "https://api.github.com/repos/4geo/web-dev/forks", "full_name": "4geo/web-dev", "git_commits_url": "https://api.github.com/repos/4geo/web-dev/git/commits{/sha}", "git_refs_url": "https://api.github.com/repos/4geo/web-dev/git/refs{/sha}", "git_tags_url": "https://api.github.com/repos/4geo/web-dev/git/tags{/sha}", "git_url": "git://github.com/4geo/web-dev.git", "has_downloads": true, "has_issues": false, "has_wiki": false, "homepage": null, "hooks_url": "https://api.github.com/repos/4geo/web-dev/hooks", "html_url": "https://github.com/4geo/web-dev", "id": 5610301, "issue_comment_url": "https://api.github.com/repos/4geo/web-dev/issues/comments/{number}", "issue_events_url": "https://api.github.com/repos/4geo/web-dev/issues/events{/number}", "issues_url": "https://api.github.com/repos/4geo/web-dev/issues{/number}", "keys_url": "https://api.github.com/repos/4geo/web-dev/keys{/key_id}", "labels_url": "https://api.github.com/repos/4geo/web-dev/labels{/name}", "language": "JavaScript", "languages_url": "https://api.github.com/repos/4geo/web-dev/languages", "master_branch": "release", "merges_url": "https://api.github.com/repos/4geo/web-dev/merges", "milestones_url": "https://api.github.com/repos/4geo/web-dev/milestones{/number}", "mirror_url": null, "name": "web-dev", "notifications_url": "https://api.github.com/repos/4geo/web-dev/notifications{?since,all,participating}", "open_issues": 4, "open_issues_count": 4, "owner": { "avatar_url": "https://secure.gravatar.com/avatar/d41d8cd98f00b204e9800998ecf8427e?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-org-420.png", "events_url": "https://api.github.com/users/4geo/events{/privacy}", "followers_url": "https://api.github.com/users/4geo/followers", "following_url": "https://api.github.com/users/4geo/following", "gists_url": "https://api.github.com/users/4geo/gists{/gist_id}", "gravatar_id": "d41d8cd98f00b204e9800998ecf8427e", "html_url": "https://github.com/4geo", "id": 2161276, "login": "4geo", "organizations_url": "https://api.github.com/users/4geo/orgs", "received_events_url": "https://api.github.com/users/4geo/received_events", "repos_url": "https://api.github.com/users/4geo/repos", "starred_url": "https://api.github.com/users/4geo/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/4geo/subscriptions", "type": "Organization", "url": "https://api.github.com/users/4geo" }, "private": true, "pulls_url": "https://api.github.com/repos/4geo/web-dev/pulls{/number}", "pushed_at": "2013-02-22T06:50:05Z", "size": 660, "ssh_url": "git@github.com:4geo/web-dev.git", "stargazers_url": "https://api.github.com/repos/4geo/web-dev/stargazers", "statuses_url": "https://api.github.com/repos/4geo/web-dev/statuses/{sha}", "subscribers_url": "https://api.github.com/repos/4geo/web-dev/subscribers", "subscription_url": "https://api.github.com/repos/4geo/web-dev/subscription", "svn_url": "https://github.com/4geo/web-dev", "tags_url": "https://api.github.com/repos/4geo/web-dev/tags{/tag}", "teams_url": "https://api.github.com/repos/4geo/web-dev/teams", "trees_url": "https://api.github.com/repos/4geo/web-dev/git/trees{/sha}", "updated_at": "2013-02-22T06:50:06Z", "url": "https://api.github.com/repos/4geo/web-dev", "watchers": 0, "watchers_count": 0 }, "sender": { "avatar_url": "https://secure.gravatar.com/avatar/c3e2bd444cac0a23aa591921b4d1a8f1?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png", "events_url": "https://api.github.com/users/caiiiycuk/events{/privacy}", "followers_url": "https://api.github.com/users/caiiiycuk/followers", "following_url": "https://api.github.com/users/caiiiycuk/following", "gists_url": "https://api.github.com/users/caiiiycuk/gists{/gist_id}", "gravatar_id": "c3e2bd444cac0a23aa591921b4d1a8f1", "html_url": "https://github.com/caiiiycuk", "id": 1727152, "login": "caiiiycuk", "organizations_url": "https://api.github.com/users/caiiiycuk/orgs", "received_events_url": "https://api.github.com/users/caiiiycuk/received_events", "repos_url": "https://api.github.com/users/caiiiycuk/repos", "starred_url": "https://api.github.com/users/caiiiycuk/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/caiiiycuk/subscriptions", "type": "User", "url": "https://api.github.com/users/caiiiycuk" } }
"""

  val payload3 =
    """
{ "action": "synchronize", "number": 187, "pull_request": { "_links": { "comments": { "href": "https://api.github.com/repos/4geo/web-dev/issues/187/comments" }, "html": { "href": "https://github.com/4geo/web-dev/pull/187" }, "issue": { "href": "https://api.github.com/repos/4geo/web-dev/issues/187" }, "review_comments": { "href": "https://api.github.com/repos/4geo/web-dev/pulls/187/comments" }, "self": { "href": "https://api.github.com/repos/4geo/web-dev/pulls/187" } }, "additions": 3, "assignee": null, "base": { "label": "4geo:release", "ref": "release", "repo": { "archive_url": "https://api.github.com/repos/4geo/web-dev/{archive_format}{/ref}", "assignees_url": "https://api.github.com/repos/4geo/web-dev/assignees{/user}", "blobs_url": "https://api.github.com/repos/4geo/web-dev/git/blobs{/sha}", "branches_url": "https://api.github.com/repos/4geo/web-dev/branches{/branch}", "clone_url": "https://github.com/4geo/web-dev.git", "collaborators_url": "https://api.github.com/repos/4geo/web-dev/collaborators{/collaborator}", "comments_url": "https://api.github.com/repos/4geo/web-dev/comments{/number}", "commits_url": "https://api.github.com/repos/4geo/web-dev/commits{/sha}", "compare_url": "https://api.github.com/repos/4geo/web-dev/compare/{base}...{head}", "contents_url": "https://api.github.com/repos/4geo/web-dev/contents/{+path}", "contributors_url": "https://api.github.com/repos/4geo/web-dev/contributors", "created_at": "2012-08-30T04:07:59Z", "default_branch": "release", "description": "web-dev", "downloads_url": "https://api.github.com/repos/4geo/web-dev/downloads", "events_url": "https://api.github.com/repos/4geo/web-dev/events", "fork": false, "forks": 5, "forks_count": 5, "forks_url": "https://api.github.com/repos/4geo/web-dev/forks", "full_name": "4geo/web-dev", "git_commits_url": "https://api.github.com/repos/4geo/web-dev/git/commits{/sha}", "git_refs_url": "https://api.github.com/repos/4geo/web-dev/git/refs{/sha}", "git_tags_url": "https://api.github.com/repos/4geo/web-dev/git/tags{/sha}", "git_url": "git://github.com/4geo/web-dev.git", "has_downloads": true, "has_issues": false, "has_wiki": false, "homepage": null, "hooks_url": "https://api.github.com/repos/4geo/web-dev/hooks", "html_url": "https://github.com/4geo/web-dev", "id": 5610301, "issue_comment_url": "https://api.github.com/repos/4geo/web-dev/issues/comments/{number}", "issue_events_url": "https://api.github.com/repos/4geo/web-dev/issues/events{/number}", "issues_url": "https://api.github.com/repos/4geo/web-dev/issues{/number}", "keys_url": "https://api.github.com/repos/4geo/web-dev/keys{/key_id}", "labels_url": "https://api.github.com/repos/4geo/web-dev/labels{/name}", "language": "JavaScript", "languages_url": "https://api.github.com/repos/4geo/web-dev/languages", "master_branch": "release", "merges_url": "https://api.github.com/repos/4geo/web-dev/merges", "milestones_url": "https://api.github.com/repos/4geo/web-dev/milestones{/number}", "mirror_url": null, "name": "web-dev", "notifications_url": "https://api.github.com/repos/4geo/web-dev/notifications{?since,all,participating}", "open_issues": 4, "open_issues_count": 4, "owner": { "avatar_url": "https://secure.gravatar.com/avatar/d41d8cd98f00b204e9800998ecf8427e?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-org-420.png", "events_url": "https://api.github.com/users/4geo/events{/privacy}", "followers_url": "https://api.github.com/users/4geo/followers", "following_url": "https://api.github.com/users/4geo/following", "gists_url": "https://api.github.com/users/4geo/gists{/gist_id}", "gravatar_id": "d41d8cd98f00b204e9800998ecf8427e", "html_url": "https://github.com/4geo", "id": 2161276, "login": "4geo", "organizations_url": "https://api.github.com/users/4geo/orgs", "received_events_url": "https://api.github.com/users/4geo/received_events", "repos_url": "https://api.github.com/users/4geo/repos", "starred_url": "https://api.github.com/users/4geo/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/4geo/subscriptions", "type": "Organization", "url": "https://api.github.com/users/4geo" }, "private": true, "pulls_url": "https://api.github.com/repos/4geo/web-dev/pulls{/number}", "pushed_at": "2013-02-22T06:50:05Z", "size": 660, "ssh_url": "git@github.com:4geo/web-dev.git", "stargazers_url": "https://api.github.com/repos/4geo/web-dev/stargazers", "statuses_url": "https://api.github.com/repos/4geo/web-dev/statuses/{sha}", "subscribers_url": "https://api.github.com/repos/4geo/web-dev/subscribers", "subscription_url": "https://api.github.com/repos/4geo/web-dev/subscription", "svn_url": "https://github.com/4geo/web-dev", "tags_url": "https://api.github.com/repos/4geo/web-dev/tags{/tag}", "teams_url": "https://api.github.com/repos/4geo/web-dev/teams", "trees_url": "https://api.github.com/repos/4geo/web-dev/git/trees{/sha}", "updated_at": "2013-02-22T06:50:06Z", "url": "https://api.github.com/repos/4geo/web-dev", "watchers": 0, "watchers_count": 0 }, "sha": "f9e390dd24b606f46f749791f5d03b58e5dddfc7", "user": { "avatar_url": "https://secure.gravatar.com/avatar/d41d8cd98f00b204e9800998ecf8427e?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-org-420.png", "events_url": "https://api.github.com/users/4geo/events{/privacy}", "followers_url": "https://api.github.com/users/4geo/followers", "following_url": "https://api.github.com/users/4geo/following", "gists_url": "https://api.github.com/users/4geo/gists{/gist_id}", "gravatar_id": "d41d8cd98f00b204e9800998ecf8427e", "html_url": "https://github.com/4geo", "id": 2161276, "login": "4geo", "organizations_url": "https://api.github.com/users/4geo/orgs", "received_events_url": "https://api.github.com/users/4geo/received_events", "repos_url": "https://api.github.com/users/4geo/repos", "starred_url": "https://api.github.com/users/4geo/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/4geo/subscriptions", "type": "Organization", "url": "https://api.github.com/users/4geo" } }, "body": "", "changed_files": 4, "closed_at": null, "comments": 0, "comments_url": "https://api.github.com/repos/4geo/web-dev/issues/187/comments", "commits": 2, "commits_url": "https://github.com/4geo/web-dev/pull/187/commits", "created_at": "2013-02-25T01:54:30Z", "deletions": 143, "diff_url": "https://github.com/4geo/web-dev/pull/187.diff", "head": { "label": "caiiiycuk:events", "ref": "events", "repo": { "archive_url": "https://api.github.com/repos/caiiiycuk/web-dev/{archive_format}{/ref}", "assignees_url": "https://api.github.com/repos/caiiiycuk/web-dev/assignees{/user}", "blobs_url": "https://api.github.com/repos/caiiiycuk/web-dev/git/blobs{/sha}", "branches_url": "https://api.github.com/repos/caiiiycuk/web-dev/branches{/branch}", "clone_url": "https://github.com/caiiiycuk/web-dev.git", "collaborators_url": "https://api.github.com/repos/caiiiycuk/web-dev/collaborators{/collaborator}", "comments_url": "https://api.github.com/repos/caiiiycuk/web-dev/comments{/number}", "commits_url": "https://api.github.com/repos/caiiiycuk/web-dev/commits{/sha}", "compare_url": "https://api.github.com/repos/caiiiycuk/web-dev/compare/{base}...{head}", "contents_url": "https://api.github.com/repos/caiiiycuk/web-dev/contents/{+path}", "contributors_url": "https://api.github.com/repos/caiiiycuk/web-dev/contributors", "created_at": "2012-09-11T03:03:45Z", "default_branch": "release", "description": "web-dev", "downloads_url": "https://api.github.com/repos/caiiiycuk/web-dev/downloads", "events_url": "https://api.github.com/repos/caiiiycuk/web-dev/events", "fork": true, "forks": 0, "forks_count": 0, "forks_url": "https://api.github.com/repos/caiiiycuk/web-dev/forks", "full_name": "caiiiycuk/web-dev", "git_commits_url": "https://api.github.com/repos/caiiiycuk/web-dev/git/commits{/sha}", "git_refs_url": "https://api.github.com/repos/caiiiycuk/web-dev/git/refs{/sha}", "git_tags_url": "https://api.github.com/repos/caiiiycuk/web-dev/git/tags{/sha}", "git_url": "git://github.com/caiiiycuk/web-dev.git", "has_downloads": true, "has_issues": false, "has_wiki": false, "homepage": null, "hooks_url": "https://api.github.com/repos/caiiiycuk/web-dev/hooks", "html_url": "https://github.com/caiiiycuk/web-dev", "id": 5759212, "issue_comment_url": "https://api.github.com/repos/caiiiycuk/web-dev/issues/comments/{number}", "issue_events_url": "https://api.github.com/repos/caiiiycuk/web-dev/issues/events{/number}", "issues_url": "https://api.github.com/repos/caiiiycuk/web-dev/issues{/number}", "keys_url": "https://api.github.com/repos/caiiiycuk/web-dev/keys{/key_id}", "labels_url": "https://api.github.com/repos/caiiiycuk/web-dev/labels{/name}", "language": "JavaScript", "languages_url": "https://api.github.com/repos/caiiiycuk/web-dev/languages", "master_branch": "release", "merges_url": "https://api.github.com/repos/caiiiycuk/web-dev/merges", "milestones_url": "https://api.github.com/repos/caiiiycuk/web-dev/milestones{/number}", "mirror_url": null, "name": "web-dev", "notifications_url": "https://api.github.com/repos/caiiiycuk/web-dev/notifications{?since,all,participating}", "open_issues": 0, "open_issues_count": 0, "owner": { "avatar_url": "https://secure.gravatar.com/avatar/c3e2bd444cac0a23aa591921b4d1a8f1?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png", "events_url": "https://api.github.com/users/caiiiycuk/events{/privacy}", "followers_url": "https://api.github.com/users/caiiiycuk/followers", "following_url": "https://api.github.com/users/caiiiycuk/following", "gists_url": "https://api.github.com/users/caiiiycuk/gists{/gist_id}", "gravatar_id": "c3e2bd444cac0a23aa591921b4d1a8f1", "html_url": "https://github.com/caiiiycuk", "id": 1727152, "login": "caiiiycuk", "organizations_url": "https://api.github.com/users/caiiiycuk/orgs", "received_events_url": "https://api.github.com/users/caiiiycuk/received_events", "repos_url": "https://api.github.com/users/caiiiycuk/repos", "starred_url": "https://api.github.com/users/caiiiycuk/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/caiiiycuk/subscriptions", "type": "User", "url": "https://api.github.com/users/caiiiycuk" }, "private": true, "pulls_url": "https://api.github.com/repos/caiiiycuk/web-dev/pulls{/number}", "pushed_at": "2013-02-25T02:39:23Z", "size": 340, "ssh_url": "git@github.com:caiiiycuk/web-dev.git", "stargazers_url": "https://api.github.com/repos/caiiiycuk/web-dev/stargazers", "statuses_url": "https://api.github.com/repos/caiiiycuk/web-dev/statuses/{sha}", "subscribers_url": "https://api.github.com/repos/caiiiycuk/web-dev/subscribers", "subscription_url": "https://api.github.com/repos/caiiiycuk/web-dev/subscription", "svn_url": "https://github.com/caiiiycuk/web-dev", "tags_url": "https://api.github.com/repos/caiiiycuk/web-dev/tags{/tag}", "teams_url": "https://api.github.com/repos/caiiiycuk/web-dev/teams", "trees_url": "https://api.github.com/repos/caiiiycuk/web-dev/git/trees{/sha}", "updated_at": "2013-02-25T02:39:24Z", "url": "https://api.github.com/repos/caiiiycuk/web-dev", "watchers": 0, "watchers_count": 0 }, "sha": "5b55d01b1bea714cdebf420c0488636f5638ced7", "user": { "avatar_url": "https://secure.gravatar.com/avatar/c3e2bd444cac0a23aa591921b4d1a8f1?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png", "events_url": "https://api.github.com/users/caiiiycuk/events{/privacy}", "followers_url": "https://api.github.com/users/caiiiycuk/followers", "following_url": "https://api.github.com/users/caiiiycuk/following", "gists_url": "https://api.github.com/users/caiiiycuk/gists{/gist_id}", "gravatar_id": "c3e2bd444cac0a23aa591921b4d1a8f1", "html_url": "https://github.com/caiiiycuk", "id": 1727152, "login": "caiiiycuk", "organizations_url": "https://api.github.com/users/caiiiycuk/orgs", "received_events_url": "https://api.github.com/users/caiiiycuk/received_events", "repos_url": "https://api.github.com/users/caiiiycuk/repos", "starred_url": "https://api.github.com/users/caiiiycuk/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/caiiiycuk/subscriptions", "type": "User", "url": "https://api.github.com/users/caiiiycuk" } }, "html_url": "https://github.com/4geo/web-dev/pull/187", "id": 4296543, "issue_url": "https://github.com/4geo/web-dev/issues/187", "merge_commit_sha": "4e7596616131401c37d7477e41c443ada0a3a3e0", "mergeable": null, "mergeable_state": "unknown", "merged": false, "merged_at": null, "merged_by": null, "milestone": null, "number": 187, "patch_url": "https://github.com/4geo/web-dev/pull/187.patch", "review_comment_url": "/repos/4geo/web-dev/pulls/comments/{number}", "review_comments": 0, "review_comments_url": "https://github.com/4geo/web-dev/pull/187/comments", "state": "open", "title": "Test 1", "updated_at": "2013-02-25T02:39:24Z", "url": "https://api.github.com/repos/4geo/web-dev/pulls/187", "user": { "avatar_url": "https://secure.gravatar.com/avatar/c3e2bd444cac0a23aa591921b4d1a8f1?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png", "events_url": "https://api.github.com/users/caiiiycuk/events{/privacy}", "followers_url": "https://api.github.com/users/caiiiycuk/followers", "following_url": "https://api.github.com/users/caiiiycuk/following", "gists_url": "https://api.github.com/users/caiiiycuk/gists{/gist_id}", "gravatar_id": "c3e2bd444cac0a23aa591921b4d1a8f1", "html_url": "https://github.com/caiiiycuk", "id": 1727152, "login": "caiiiycuk", "organizations_url": "https://api.github.com/users/caiiiycuk/orgs", "received_events_url": "https://api.github.com/users/caiiiycuk/received_events", "repos_url": "https://api.github.com/users/caiiiycuk/repos", "starred_url": "https://api.github.com/users/caiiiycuk/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/caiiiycuk/subscriptions", "type": "User", "url": "https://api.github.com/users/caiiiycuk" } }, "repository": { "archive_url": "https://api.github.com/repos/4geo/web-dev/{archive_format}{/ref}", "assignees_url": "https://api.github.com/repos/4geo/web-dev/assignees{/user}", "blobs_url": "https://api.github.com/repos/4geo/web-dev/git/blobs{/sha}", "branches_url": "https://api.github.com/repos/4geo/web-dev/branches{/branch}", "clone_url": "https://github.com/4geo/web-dev.git", "collaborators_url": "https://api.github.com/repos/4geo/web-dev/collaborators{/collaborator}", "comments_url": "https://api.github.com/repos/4geo/web-dev/comments{/number}", "commits_url": "https://api.github.com/repos/4geo/web-dev/commits{/sha}", "compare_url": "https://api.github.com/repos/4geo/web-dev/compare/{base}...{head}", "contents_url": "https://api.github.com/repos/4geo/web-dev/contents/{+path}", "contributors_url": "https://api.github.com/repos/4geo/web-dev/contributors", "created_at": "2012-08-30T04:07:59Z", "default_branch": "release", "description": "web-dev", "downloads_url": "https://api.github.com/repos/4geo/web-dev/downloads", "events_url": "https://api.github.com/repos/4geo/web-dev/events", "fork": false, "forks": 5, "forks_count": 5, "forks_url": "https://api.github.com/repos/4geo/web-dev/forks", "full_name": "4geo/web-dev", "git_commits_url": "https://api.github.com/repos/4geo/web-dev/git/commits{/sha}", "git_refs_url": "https://api.github.com/repos/4geo/web-dev/git/refs{/sha}", "git_tags_url": "https://api.github.com/repos/4geo/web-dev/git/tags{/sha}", "git_url": "git://github.com/4geo/web-dev.git", "has_downloads": true, "has_issues": false, "has_wiki": false, "homepage": null, "hooks_url": "https://api.github.com/repos/4geo/web-dev/hooks", "html_url": "https://github.com/4geo/web-dev", "id": 5610301, "issue_comment_url": "https://api.github.com/repos/4geo/web-dev/issues/comments/{number}", "issue_events_url": "https://api.github.com/repos/4geo/web-dev/issues/events{/number}", "issues_url": "https://api.github.com/repos/4geo/web-dev/issues{/number}", "keys_url": "https://api.github.com/repos/4geo/web-dev/keys{/key_id}", "labels_url": "https://api.github.com/repos/4geo/web-dev/labels{/name}", "language": "JavaScript", "languages_url": "https://api.github.com/repos/4geo/web-dev/languages", "master_branch": "release", "merges_url": "https://api.github.com/repos/4geo/web-dev/merges", "milestones_url": "https://api.github.com/repos/4geo/web-dev/milestones{/number}", "mirror_url": null, "name": "web-dev", "notifications_url": "https://api.github.com/repos/4geo/web-dev/notifications{?since,all,participating}", "open_issues": 4, "open_issues_count": 4, "owner": { "avatar_url": "https://secure.gravatar.com/avatar/d41d8cd98f00b204e9800998ecf8427e?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-org-420.png", "events_url": "https://api.github.com/users/4geo/events{/privacy}", "followers_url": "https://api.github.com/users/4geo/followers", "following_url": "https://api.github.com/users/4geo/following", "gists_url": "https://api.github.com/users/4geo/gists{/gist_id}", "gravatar_id": "d41d8cd98f00b204e9800998ecf8427e", "html_url": "https://github.com/4geo", "id": 2161276, "login": "4geo", "organizations_url": "https://api.github.com/users/4geo/orgs", "received_events_url": "https://api.github.com/users/4geo/received_events", "repos_url": "https://api.github.com/users/4geo/repos", "starred_url": "https://api.github.com/users/4geo/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/4geo/subscriptions", "type": "Organization", "url": "https://api.github.com/users/4geo" }, "private": true, "pulls_url": "https://api.github.com/repos/4geo/web-dev/pulls{/number}", "pushed_at": "2013-02-22T06:50:05Z", "size": 660, "ssh_url": "git@github.com:4geo/web-dev.git", "stargazers_url": "https://api.github.com/repos/4geo/web-dev/stargazers", "statuses_url": "https://api.github.com/repos/4geo/web-dev/statuses/{sha}", "subscribers_url": "https://api.github.com/repos/4geo/web-dev/subscribers", "subscription_url": "https://api.github.com/repos/4geo/web-dev/subscription", "svn_url": "https://github.com/4geo/web-dev", "tags_url": "https://api.github.com/repos/4geo/web-dev/tags{/tag}", "teams_url": "https://api.github.com/repos/4geo/web-dev/teams", "trees_url": "https://api.github.com/repos/4geo/web-dev/git/trees{/sha}", "updated_at": "2013-02-22T06:50:06Z", "url": "https://api.github.com/repos/4geo/web-dev", "watchers": 0, "watchers_count": 0 }, "sender": { "avatar_url": "https://secure.gravatar.com/avatar/c3e2bd444cac0a23aa591921b4d1a8f1?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png", "events_url": "https://api.github.com/users/caiiiycuk/events{/privacy}", "followers_url": "https://api.github.com/users/caiiiycuk/followers", "following_url": "https://api.github.com/users/caiiiycuk/following", "gists_url": "https://api.github.com/users/caiiiycuk/gists{/gist_id}", "gravatar_id": "c3e2bd444cac0a23aa591921b4d1a8f1", "html_url": "https://github.com/caiiiycuk", "id": 1727152, "login": "caiiiycuk", "organizations_url": "https://api.github.com/users/caiiiycuk/orgs", "received_events_url": "https://api.github.com/users/caiiiycuk/received_events", "repos_url": "https://api.github.com/users/caiiiycuk/repos", "starred_url": "https://api.github.com/users/caiiiycuk/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/caiiiycuk/subscriptions", "type": "User", "url": "https://api.github.com/users/caiiiycuk" } }
"""

  def main(args: Array[String]) {
    AdviceChecks.update()
    new UnlintHook().hook(payload3, "55d49cb0042c5ad0635380d3c5e5d961d4540b09")
    //    Routes.error = classOf[Errors]
    //    Routes.sockJs(classOf[UnlintSock], "unlint")
    //    Server.start()
  }
}
